### ISSUE TITLE
LZQ&LYD YYDS！！

### ISSUE THREAD

**Issue by luosiallen** [lzqv5/Artificial-Intelligence-DATA130008.01-2020-Fall#1]

**Comment by luosiallen** [comment]
Great Job！Make significant contribution to the cause of 'involution' in SDS.

**Comment by lzqv5** [comment]
> Great Job！Make significant contribution to the cause of 'involution' in SDS.

That's everyone's duty of SDS. lol

**Comment by Wandou72** [comment]
> > Great Job！Make significant contribution to the cause of 'involution' in SDS.
> 
> That's everyone's duty of SDS. lol

> But you guys are really distinguished!
